/* Generated By:JJTree: Do not edit this line. ASTConstantAssign.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTConstantAssign extends SimpleNode {
  public ASTConstantAssign(int id) {
    super(id);
  }

  public ASTConstantAssign(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=fccdb93c23a9625d7ed106b21f032d05 (do not edit this line) */
