/* Generated By:JJTree: Do not edit this line. ASTFunctionReturn.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTFunctionReturn extends SimpleNode {
  public ASTFunctionReturn(int id) {
    super(id);
  }

  public ASTFunctionReturn(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=eb3f82a8ccf32f099e2a8e6b16f9d213 (do not edit this line) */
