/* Generated By:JJTree: Do not edit this line. ASTGreaterOrEqualOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGreaterOrEqualOperator extends SimpleNode {
  public ASTGreaterOrEqualOperator(int id) {
    super(id);
  }

  public ASTGreaterOrEqualOperator(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b5b3db0560c42d982e2bc4426b2d30a9 (do not edit this line) */
