/* Generated By:JJTree: Do not edit this line. ASTGreaterThanOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTGreaterThanOperator extends SimpleNode {
  public ASTGreaterThanOperator(int id) {
    super(id);
  }

  public ASTGreaterThanOperator(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=c7386872d9204697d3042d681ee5ab8a (do not edit this line) */
