/* Generated By:JJTree&JavaCC: Do not edit this line. MyParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int VARIABLE = 11;
  /** RegularExpression Id. */
  int CONSTANT = 12;
  /** RegularExpression Id. */
  int RETURN = 13;
  /** RegularExpression Id. */
  int INTEGER = 14;
  /** RegularExpression Id. */
  int BOOLEAN = 15;
  /** RegularExpression Id. */
  int VOID = 16;
  /** RegularExpression Id. */
  int MAIN = 17;
  /** RegularExpression Id. */
  int IF = 18;
  /** RegularExpression Id. */
  int ELSE = 19;
  /** RegularExpression Id. */
  int TRUE = 20;
  /** RegularExpression Id. */
  int FALSE = 21;
  /** RegularExpression Id. */
  int WHILE = 22;
  /** RegularExpression Id. */
  int BEGIN = 23;
  /** RegularExpression Id. */
  int END = 24;
  /** RegularExpression Id. */
  int IS = 25;
  /** RegularExpression Id. */
  int SKIPPY = 26;
  /** RegularExpression Id. */
  int COMMA = 27;
  /** RegularExpression Id. */
  int SEMICOL = 28;
  /** RegularExpression Id. */
  int COLON = 29;
  /** RegularExpression Id. */
  int ASSIGN = 30;
  /** RegularExpression Id. */
  int L_BRACK = 31;
  /** RegularExpression Id. */
  int R_BRACK = 32;
  /** RegularExpression Id. */
  int PLUS = 33;
  /** RegularExpression Id. */
  int MINUS = 34;
  /** RegularExpression Id. */
  int BITNOT = 35;
  /** RegularExpression Id. */
  int BITOR = 36;
  /** RegularExpression Id. */
  int BITAND = 37;
  /** RegularExpression Id. */
  int EQUAL = 38;
  /** RegularExpression Id. */
  int N_EQUAL = 39;
  /** RegularExpression Id. */
  int L_THAN = 40;
  /** RegularExpression Id. */
  int L_OR_EQU = 41;
  /** RegularExpression Id. */
  int G_THAN = 42;
  /** RegularExpression Id. */
  int G_OR_EQU = 43;
  /** RegularExpression Id. */
  int DIGIT = 44;
  /** RegularExpression Id. */
  int CHAR = 45;
  /** RegularExpression Id. */
  int NUM = 46;
  /** RegularExpression Id. */
  int ID = 47;
  /** RegularExpression Id. */
  int OTHER = 48;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_COMMENT = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\f\"",
    "\"/*\"",
    "<token of kind 7>",
    "\"/*\"",
    "\"*/\"",
    "<token of kind 10>",
    "\"variable\"",
    "\"constant\"",
    "\"return\"",
    "\"integer\"",
    "\"boolean\"",
    "\"void\"",
    "\"main\"",
    "\"if\"",
    "\"else\"",
    "\"true\"",
    "\"false\"",
    "\"while\"",
    "\"begin\"",
    "\"end\"",
    "\"is\"",
    "\"skip\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\":=\"",
    "\"(\"",
    "\")\"",
    "\"+\"",
    "\"-\"",
    "\"~\"",
    "\"|\"",
    "\"&\"",
    "\"=\"",
    "\"!=\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "<DIGIT>",
    "<CHAR>",
    "<NUM>",
    "<ID>",
    "<OTHER>",
  };

}
