/* Generated By:JavaCC: Do not edit this line. MyParserVisitor.java Version 5.0 */
public interface MyParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTProgram node, Object data);
  public Object visit(ASTVariableDeclaration node, Object data);
  public Object visit(ASTConstantDeclaration node, Object data);
  public Object visit(ASTConstantAssign node, Object data);
  public Object visit(ASTFunction node, Object data);
  public Object visit(ASTFunctionReturn node, Object data);
  public Object visit(ASTType node, Object data);
  public Object visit(ASTParameterList node, Object data);
  public Object visit(ASTMain node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTPlusOperator node, Object data);
  public Object visit(ASTMinusOperator node, Object data);
  public Object visit(ASTBitOrOperator node, Object data);
  public Object visit(ASTBitAndOperator node, Object data);
  public Object visit(ASTEqualOperator node, Object data);
  public Object visit(ASTNotEqualOperator node, Object data);
  public Object visit(ASTLessThanOperator node, Object data);
  public Object visit(ASTLessOrEqualOperator node, Object data);
  public Object visit(ASTGreaterThanOperator node, Object data);
  public Object visit(ASTGreaterOrEqualOperator node, Object data);
  public Object visit(ASTArgumentList node, Object data);
  public Object visit(ASTIdentifier node, Object data);
  public Object visit(ASTBoolean node, Object data);
  public Object visit(ASTNumber node, Object data);
}
/* JavaCC - OriginalChecksum=be7c2175834dbe3f0094be5419de9728 (do not edit this line) */
