/* Generated By:JavaCC: Do not edit this line. MyParserTreeConstants.java Version 5.0 */
public interface MyParserTreeConstants
{
  public int JJTPROGRAM = 0;
  public int JJTVOID = 1;
  public int JJTVARIABLEDECLARATION = 2;
  public int JJTCONSTANTDECLARATION = 3;
  public int JJTCONSTANTASSIGN = 4;
  public int JJTFUNCTION = 5;
  public int JJTFUNCTIONRETURN = 6;
  public int JJTTYPE = 7;
  public int JJTPARAMETERLIST = 8;
  public int JJTMAIN = 9;
  public int JJTSTATEMENT = 10;
  public int JJTPLUSOPERATOR = 11;
  public int JJTMINUSOPERATOR = 12;
  public int JJTBITOROPERATOR = 13;
  public int JJTBITANDOPERATOR = 14;
  public int JJTEQUALOPERATOR = 15;
  public int JJTNOTEQUALOPERATOR = 16;
  public int JJTLESSTHANOPERATOR = 17;
  public int JJTLESSOREQUALOPERATOR = 18;
  public int JJTGREATERTHANOPERATOR = 19;
  public int JJTGREATEROREQUALOPERATOR = 20;
  public int JJTARGUMENTLIST = 21;
  public int JJTIDENTIFIER = 22;
  public int JJTBOOLEAN = 23;
  public int JJTNUMBER = 24;


  public String[] jjtNodeName = {
    "Program",
    "void",
    "VariableDeclaration",
    "ConstantDeclaration",
    "ConstantAssign",
    "Function",
    "FunctionReturn",
    "Type",
    "ParameterList",
    "Main",
    "Statement",
    "PlusOperator",
    "MinusOperator",
    "BitOrOperator",
    "BitAndOperator",
    "EqualOperator",
    "NotEqualOperator",
    "LessThanOperator",
    "LessOrEqualOperator",
    "GreaterThanOperator",
    "GreaterOrEqualOperator",
    "ArgumentList",
    "Identifier",
    "Boolean",
    "Number",
  };
}
/* JavaCC - OriginalChecksum=ac201035c0000e7158cb6ed0647eab61 (do not edit this line) */
