/* Generated By:JJTree: Do not edit this line. ASTBitAndOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBitAndOperator extends SimpleNode {
  public ASTBitAndOperator(int id) {
    super(id);
  }

  public ASTBitAndOperator(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=02b5674685a98951761ce561c6bd9330 (do not edit this line) */
