/* Generated By:JJTree: Do not edit this line. ASTBitOrOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTBitOrOperator extends SimpleNode {
  public ASTBitOrOperator(int id) {
    super(id);
  }

  public ASTBitOrOperator(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=41e54c46f76be216ef4b2313267c6188 (do not edit this line) */
