/* Generated By:JJTree: Do not edit this line. ASTLessOrEqualOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTLessOrEqualOperator extends SimpleNode {
  public ASTLessOrEqualOperator(int id) {
    super(id);
  }

  public ASTLessOrEqualOperator(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=12c8c25c21910564e3acdb754522994e (do not edit this line) */
