/* Generated By:JJTree: Do not edit this line. ASTPlusOperator.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class ASTPlusOperator extends SimpleNode {
  public ASTPlusOperator(int id) {
    super(id);
  }

  public ASTPlusOperator(MyParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(MyParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=3d6e6fc81d85ae85f39cb7306abfa794 (do not edit this line) */
